### ISSUE TITLE
reflect panic: unexported field

### ISSUE THREAD

**Issue by Playit3110** [rschone/corefile2struct#1]
My struct is:
```go
type Config struct {
    Arguments []strings
    db string `cf:"db" check:"nonempty"`
}
var config Config
```

`panic: reflect: reflect.Value.SetString obtained using unexported field`

How can I fix this

**Comment by rschone** [comment]
The first letter of each field in the structure has to be uppercased (=exported) as a reflection is used for accessing it. Otherwise, the reflection wouldn't have access to this field.
In your case, there must be `Db string`.
Did it help?

**Comment by Playit3110** [comment]
Thank you, im learning go right now so i forgot.
